import NavbarComponent from '@/components/NavbarComponent`'
import './globals.css'
import { Inter } from 'next/font/google'
import ProviderRedux from '@/redux/ProiderRedux`'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Redux',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderRedux>
          <NavbarComponent />
          {children}
        </ProviderRedux>
      </body>
    </html>
  )
}
